/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManufacturerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InspectionOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InspectionWorkRequest;
import Business.WorkQueue.ManufacturingWorkRequest;
import Business.WorkQueue.OrphanagePackage;
import Business.WorkQueue.SchoolPackage;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author deekshakhajuria
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
     private EcoSystem system;
     private UserAccount account;
     private Enterprise enterprise;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer,EcoSystem system,UserAccount account,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.enterprise= enterprise;
    
         jLabel3.setVisible(false);
         jLabel4.setVisible(false);
         jLabel5.setVisible(false);
         jLabel6.setVisible(false);
         jLabel7.setVisible(false);
            
          jTextField1.setVisible(false);
          jTextField2.setVisible(false);
          jTextField3.setVisible(false);
          jTextField4.setVisible(false);
          jTextField5.setVisible(false);  
          processinspectionJText.setEnabled(false);
          processinspectionJText.setVisible(false);
          submitJButton.setVisible(false);
}
    
     static boolean isNumberValid(String number)
    {
        String regex = "[\\\\s]*[0-9]*[0-9]+";
        return number.matches(regex);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        submitJButton = new javax.swing.JButton();
        manufacturingComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        processinspectionJText = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1620, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(1620, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(1620, 900));

        submitJButton.setBackground(new java.awt.Color(0, 102, 204));
        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit Data");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        manufacturingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please choose from the below", "School Package", "Orphanage Package" }));
        manufacturingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturingComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Please Select PackageType : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("jLabel7");

        processinspectionJText.setBackground(new java.awt.Color(0, 102, 204));
        processinspectionJText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        processinspectionJText.setForeground(new java.awt.Color(255, 255, 255));
        processinspectionJText.setText("Process for Inspection");
        processinspectionJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processinspectionJTextActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("MANUFACTURING DATA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1620, Short.MAX_VALUE)
                .addComponent(jLabel10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(submitJButton)
                        .addGap(44, 44, 44)
                        .addComponent(processinspectionJText))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(jLabel8)
                            .addGap(58, 58, 58))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manufacturingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(manufacturingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitJButton)
                            .addComponent(processinspectionJText))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        jTextField1.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel3.setForeground(Color.BLACK);

        jTextField2.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel4.setForeground(Color.BLACK);

        jTextField3.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel5.setForeground(Color.BLACK);

        jTextField4.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel6.setForeground(Color.BLACK);

        jTextField5.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel7.setForeground(Color.BLACK);

        if(manufacturingComboBox.getSelectedIndex()==3)
        {
            if(isNumberValid(jTextField1.getText()) == false || jTextField1.getText() == null || jTextField1.getText().equals(""))
            {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel3.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel3.getText());
                return;
            }
        }
        else if(manufacturingComboBox.getSelectedIndex()==2){
            if(isNumberValid(jTextField1.getText()) == false || jTextField1.getText() == null || jTextField1.getText().equals(""))
            {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel3.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel3.getText());
                return;
            }
            else if(isNumberValid(jTextField2.getText()) == false || jTextField2.getText() == null || jTextField2.getText().equals(""))
            {
                jTextField2.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel4.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel4.getText());
                return;
            }
            else if(isNumberValid(jTextField3.getText()) == false || jTextField3.getText() == null || jTextField3.getText().equals(""))
            {
                jTextField3.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel5.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel5.getText());
                return;
            }
            else if(isNumberValid(jTextField4.getText()) == false || jTextField4.getText() == null || jTextField4.getText().equals(""))
            {
                jTextField4.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel6.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel6.getText());
                return;
            }
            else if(isNumberValid(jTextField5.getText()) == false || jTextField5.getText() == null || jTextField5.getText().equals(""))
            {
                jTextField5.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel7.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel7.getText());
                return;
            }
        }
        if(manufacturingComboBox.getSelectedIndex()==1)
        {
            if(isNumberValid(jTextField1.getText()) == false || jTextField1.getText() == null || jTextField1.getText().equals(""))
            {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel3.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel3.getText());
                return;
            }
            else if(isNumberValid(jTextField2.getText()) == false || jTextField2.getText() == null || jTextField2.getText().equals(""))
            {
                jTextField2.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel4.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel4.getText());
                return;
            }
            else if(isNumberValid(jTextField3.getText()) == false || jTextField3.getText() == null || jTextField3.getText().equals(""))
            {
                jTextField3.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel5.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel5.getText());
                return;
            }
            else if(isNumberValid(jTextField4.getText()) == false || jTextField4.getText() == null || jTextField4.getText().equals(""))
            {
                jTextField4.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel6.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel6.getText());
                return;
            }
        }

        ArrayList<WorkRequest> result = system.getWorkQueue().getWorkRequestList();
        ManufacturingWorkRequest manufacturingworkrequest=null;
        if(result==null || result.isEmpty()){
            manufacturingworkrequest = new ManufacturingWorkRequest();
            result.add(manufacturingworkrequest);
        }

        for (int i=0; i<result.size();i++) {
            manufacturingworkrequest = (ManufacturingWorkRequest) result.get(i);

            if(manufacturingComboBox.getSelectedIndex()==2){
                int numberOfBeds = Integer.parseInt(jTextField1.getText());
                int numberOfBlankets = Integer.parseInt(jTextField2.getText());
                int numberOfNoteBooks = Integer.parseInt(jTextField3.getText());
                int numberOfArtSupplies = Integer.parseInt(jTextField4.getText());
                int numberOfMasks = Integer.parseInt(jTextField5.getText());

                if(numberOfBeds==0&&numberOfBlankets==0&&numberOfNoteBooks==0&&numberOfArtSupplies==0&&numberOfMasks==0){
                    JOptionPane.showMessageDialog(null, "Please enter a value greater than 0");
                    return;
                }

                OrphanagePackage orphanagePackage = manufacturingworkrequest.getOrphanagePackage();
                if(orphanagePackage==null){
                    orphanagePackage = new OrphanagePackage();
                }
                numberOfBeds = numberOfBeds+((String.valueOf(orphanagePackage.getNumberOfBeds()))==null?0:orphanagePackage.getNumberOfBeds());
                orphanagePackage.setNumberOfBeds(numberOfBeds);

                numberOfBlankets = numberOfBlankets+(String.valueOf(orphanagePackage.getNumberOfBlankets())==null?0:orphanagePackage.getNumberOfBlankets());
                orphanagePackage.setNumberOfBlankets(numberOfBlankets);

                numberOfNoteBooks = numberOfNoteBooks+(String.valueOf(orphanagePackage.getNumberOfNotebooks())==null?0:orphanagePackage.getNumberOfNotebooks());
                orphanagePackage.setNumberOfNotebooks(numberOfNoteBooks);

                numberOfArtSupplies = numberOfArtSupplies+(String.valueOf(orphanagePackage.getNumberOfArtSupplies())==null?0:orphanagePackage.getNumberOfArtSupplies());
                orphanagePackage.setNumberOfArtSupplies(numberOfArtSupplies);

                numberOfMasks =numberOfMasks+(String.valueOf(orphanagePackage.getNumberOfMasks())==null?0:orphanagePackage.getNumberOfMasks());
                orphanagePackage.setNumberOfMasks(numberOfMasks);
                manufacturingworkrequest.setOrphanagePackage(orphanagePackage);
                JOptionPane.showMessageDialog(null, "Orphanage Package added Succesfully");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                return;
            }
        }
        for (Organization InspectionOrganization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            ArrayList<WorkRequest> inspectionWorklist = InspectionOrganization.getWorkQueue().getWorkRequestList();
            InspectionWorkRequest InspectionWorkRequest = null;
            if(inspectionWorklist==null || inspectionWorklist.isEmpty()){
                InspectionWorkRequest = new InspectionWorkRequest();
                inspectionWorklist.add(InspectionWorkRequest);
            }
            for(int i=0; i<inspectionWorklist.size();i++){
                InspectionWorkRequest = (InspectionWorkRequest)inspectionWorklist.get(i);
                if(manufacturingComboBox.getSelectedIndex()==1){
                    int numberOfBoards = Integer.parseInt(jTextField1.getText());
                    int numberOfTables = Integer.parseInt(jTextField2.getText());
                    int numberOfNotebooks = Integer.parseInt(jTextField3.getText());
                    int numberOfMasks = Integer.parseInt(jTextField4.getText());

                    if(numberOfBoards==0&&numberOfTables==0&&numberOfNotebooks==0&&numberOfMasks==0){
                        JOptionPane.showMessageDialog(null, "Please enter a value greater than 0");
                        return;
                    }

                    SchoolPackage schoolPackage = new SchoolPackage();
                    schoolPackage.setNumberOfBoards(numberOfBoards);
                    schoolPackage.setNumberOfTables(numberOfTables);
                    schoolPackage.setNumberOfNotebooks(numberOfNotebooks);
                    schoolPackage.setNumberOfMasks(numberOfMasks);

                    numberOfBoards = ((String.valueOf(schoolPackage.getNumberOfBoards()))==null?0:schoolPackage.getNumberOfBoards());
                    schoolPackage.setNumberOfBoards(numberOfBoards);

                    numberOfTables = ((String.valueOf(schoolPackage.getNumberOfTables()))==null?0:schoolPackage.getNumberOfTables());
                    schoolPackage.setNumberOfTables(numberOfTables);

                    numberOfNotebooks = ((String.valueOf(schoolPackage.getNumberOfNotebooks()))==null?0:schoolPackage.getNumberOfNotebooks());
                    schoolPackage.setNumberOfNotebooks(numberOfNotebooks);

                    numberOfMasks = ((String.valueOf(schoolPackage.getNumberOfMasks()))==null?0:schoolPackage.getNumberOfMasks());
                    schoolPackage.setNumberOfMasks(numberOfMasks);

                    schoolPackage.setStatus("Pending");

                    InspectionWorkRequest.setSchoolPackage(schoolPackage);
                    InspectionWorkRequest.setMessage("message");
                    InspectionWorkRequest.setSender(account);
                    InspectionWorkRequest.setStatus("Sent");

                    JOptionPane.showMessageDialog(null, "School Package added Succesfully");
                   
                    submitJButton.setEnabled(false);
                    processinspectionJText.setEnabled(true);

                }return;
            }
        }

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void manufacturingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturingComboBoxActionPerformed
       
        if(manufacturingComboBox.getSelectedIndex()==2){
            jLabel3.setVisible(true);
            jLabel3.setText("Number Of Beds");
            jLabel4.setVisible(true);
            jLabel4.setText("Number Of Blankets");
            jLabel5.setVisible(true);
            jLabel5.setText("Number Of Notebooks");
            jLabel6.setVisible(true);
            jLabel6.setText("Number Of ArtSupplies");
            jLabel7.setVisible(true);
            jLabel7.setText("Number Of Masks");
            processinspectionJText.setVisible(false);
            submitJButton.setVisible(true);
            submitJButton.setEnabled(true);

            jTextField1.setVisible(true);
            jTextField1.setText("");
            jTextField2.setVisible(true);
            jTextField2.setText("");
            jTextField3.setVisible(true);
            jTextField3.setText("");
            jTextField4.setVisible(true);
            jTextField4.setText("");
            jTextField5.setVisible(true);
            jTextField5.setText("");

        }
        else if(manufacturingComboBox.getSelectedIndex()==1){
            jLabel3.setVisible(true);
            jLabel3.setText("Number Of Boards");
            jLabel4.setVisible(true);
            jLabel4.setText("Number Of Tables");
            jLabel5.setVisible(true);
            jLabel5.setText("Number Of Notebooks");
            jLabel6.setVisible(true);
            jLabel6.setText("Number Of Masks");
            jLabel7.setVisible(false);
            processinspectionJText.setVisible(true);
            submitJButton.setVisible(true);

            jTextField1.setVisible(true);
            jTextField1.setText("");
            jTextField2.setVisible(true);
            jTextField2.setText("");
            jTextField3.setVisible(true);
            jTextField3.setText("");
            jTextField4.setVisible(true);
            jTextField4.setText("");
            jTextField5.setVisible(false);
            jTextField5.setText("");

        }
        else{
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            submitJButton.setVisible(false);
            processinspectionJText.setVisible(false);

            jTextField1.setVisible(false);
            jTextField1.setText("");
            jTextField2.setVisible(false);
            jTextField2.setText("");
            jTextField3.setVisible(false);
            jTextField3.setText("");
            jTextField4.setVisible(false);
            jTextField4.setText("");
            jTextField5.setVisible(false);
            jTextField5.setText("");

        }
    }//GEN-LAST:event_manufacturingComboBoxActionPerformed

    private void processinspectionJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processinspectionJTextActionPerformed


        InspectionWorkRequest request = new InspectionWorkRequest();
        request.setMessage("message");
        request.setSender(account);
        request.setStatus("Sent");

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof InspectionOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request raised for Inspection");
        }
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_processinspectionJTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox<String> manufacturingComboBox;
    private javax.swing.JButton processinspectionJText;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
